name: npm cache
description: 'Cache npm dependencies'

outputs:
  cache-hit:
    description: 'Whether the cache was a hit or not'
    value: ${{ steps.node_modules_cache_id.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Print node_modules_cache_id
      shell: bash
      run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
